name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Make cserver
      run: scripts/make.sh
    - name: Run tests
      run: scripts/test.sh